// Hand-authored publication records for mechanism-specific pages added after the portal redesign.
const page = (title: string, path: string, navigationSection: string, audience: string, sortOrder: number) => ({
  product: 'kingshot-events', title, path: `/kingshot-events/${path.endsWith('/index') ? `${path.replace(/\/index$/, '')}/` : path}`,
  navigationSection, audience, experienceLevel: 'Advanced', featureArea: navigationSection,
  publicationStatus: 'published', sortOrder, lastReviewedDate: '2026-08-01', file: `kingshot-events/${path}.md`
})

export const manualPages = [
  page('Getting Started', 'getting-started/index', 'Getting Started', 'New users', 15),
  page('Accounts and Access', 'accounts-and-access/index', 'Accounts and Access', 'All signed-in users', 16),
  page('Scopes and Communities', 'scopes-and-communities/index', 'Scopes and Communities', 'Members and community managers', 17),
  page('Players', 'players/index', 'Players', 'Players and roster managers', 18),
  page('Events and Results', 'events/index', 'Events and Results', 'Contributors and event reviewers', 19),
  page('Imports and Data Entry', 'imports/index', 'Imports and Data Entry', 'Contributors and import reviewers', 20),
  page('Analytics and Rewards', 'analytics/index', 'Analytics and Rewards', 'Analytics viewers and reward managers', 21),
  page('Knowledge Hub', 'knowledge-hub/index', 'Knowledge Hub', 'Readers, authors, reviewers, and session managers', 22),
  page('Troubleshooting', 'troubleshooting/index', 'Troubleshooting', 'All users', 23),
  page('Co-leader', 'role-journeys/co-leader', 'Role Journeys', 'Co-leaders', 134),
  page('Reading-session Manager', 'role-journeys/reading-session-manager', 'Role Journeys', 'Reading-session managers', 135),
  page('Notifications and Reports', 'lifecycles/notifications-and-reports', 'Platform Lifecycles', 'Members and managers', 126),
  page('Recycle Bin and Restore Requests', 'lifecycles/recycle-bin-and-restore-requests', 'Platform Lifecycles', 'Managers and restore reviewers', 127),
  page('Hierarchy and Scope Switching', 'scopes-and-communities/hierarchy-and-switching', 'Scopes and Communities', 'Members, alliance leaders, and kingdom managers', 200),
  page('Profile, Identity, Activity, and History', 'players/profile-and-history', 'Players', 'Players and roster managers', 210),
  page('Event Instances, Record Batches, and Corrections', 'events/record-batches-and-corrections', 'Events and Results', 'Result contributors and reviewers', 220),
  page('Screenshot Reconciliation and Row Decisions', 'imports/row-statuses-and-decisions', 'Imports and Data Entry', 'Import contributors and reviewers', 230),
  page('Analytics Aggregation and Reward Decisions', 'analytics/reward-rules', 'Analytics and Rewards', 'Analytics viewers and reward managers', 240),
  page('Castle Candidate Ranking and Schedule Suggestions', 'castle-positions/planner-controls', 'Castle Positions', 'Kings and Ministers of Justice', 250),
  page('Knowledge Access, Publication, and Reading Verification', 'knowledge-hub/reading-sessions', 'Knowledge Hub', 'Readers, authors, reviewers, and session managers', 260),
  page('Lab Profiles, Autosave, and Optimization Order', 'lab/profiles-and-autosave', 'Simulations and Optimizations', 'Lab users', 270),
  page('Hero Gear Optimization Logic', 'lab/hero-gear', 'Simulations and Optimizations', 'Hero Gear planner users', 271),
  page('Governor Gear Optimization Logic', 'lab/governor-gear', 'Simulations and Optimizations', 'Governor Gear planner users', 272),
  page('Charm Optimization Logic', 'lab/charms', 'Simulations and Optimizations', 'Charm planner users', 273),
  page('Bear Trap Calculation and Result Anatomy', 'lab/bear-trap', 'Simulations and Optimizations', 'Rally leaders and scenario reviewers', 274),
  page('Plans, Grants, Quotas, and Effective Access', 'subscriptions/plans-and-effective-access', 'Subscriptions and Usage', 'Members and community owners', 280),
  page('Dashboard, Alerts, and Quick Actions', 'overview/dashboard-and-alerts', 'Overview', 'Signed-in users', 285),
  page('Alliance Hub and Management', 'scopes-and-communities/alliance-hub', 'Scopes and Communities', 'Alliance members and managers', 286),
  page('Preparation and KvK Tracking', 'events/preparation-and-kvk', 'Events and Results', 'Kingdom event managers and reviewers', 287),
  page('Event Proposals, Templates, and Settings', 'events/proposals-and-settings', 'Events and Results', 'Event contributors and settings managers', 288),
  page('Reward Workspace and Personal Rewards', 'analytics/reward-workspace', 'Analytics and Rewards', 'Players and reward managers', 289),
  page('Reports and Scoped Issue Tracking', 'lifecycles/reports-and-issues', 'Platform Lifecycles', 'Members and report reviewers', 290),
  page('Privacy and Data Control Center', 'accounts-and-access/privacy-and-data-rights', 'Accounts and Access', 'Account holders and privacy reviewers', 291),
  page('Roles, Permissions, and Approval Queues', 'accounts-and-access/roles-and-approvals', 'Accounts and Access', 'Administrators and reviewers', 292),
  page('Knowledge Studio Workspaces', 'knowledge-hub/studio-workspaces', 'Knowledge Hub', 'Authors, reviewers, and Knowledge managers', 293),
  page('Rally Simulator', 'lab/rally-simulator', 'Simulations and Optimizations', 'Rally planners', 294),
  page('Battle Simulator', 'lab/battle-simulator', 'Simulations and Optimizations', 'Battle planners', 295),
  page('Game Data and Calculation Inputs', 'lab/game-data-reference', 'Simulations and Optimizations', 'Lab users and reviewers', 296),
  page('Processing Console and Provider Health', 'imports/processing-console', 'Imports and Data Entry', 'Import operators and processing administrators', 297),
  page('Subscription and Support Requests', 'subscriptions/support-requests', 'Subscriptions and Usage', 'Members and community owners', 298),
  page('Updates and Module Availability', 'updates/module-availability', 'Updates', 'Users and platform administrators', 299),
  ...[
    ['accounts-and-access/multi-role-access', 'scopes-and-communities/hierarchy-and-switching'],
    ['accounts-and-access/password-and-security', 'getting-started/first-visit'],
    ['accounts-and-access/player-link-review', 'players/profile-and-history'],
    ['accounts-and-access/registration-and-approval', 'getting-started/first-visit'],
    ['analytics/filters-and-recalculation', 'analytics/reward-rules'],
    ['analytics/recommendations-and-missing-data', 'analytics/reward-rules'],
    ['castle-positions/notifications-and-versions', 'castle-positions/planner-controls'],
    ['castle-positions/resources-and-eligibility', 'castle-positions/planner-controls'],
    ['events/custom-events-and-proposals', 'events/record-batches-and-corrections'],
    ['events/default-event-patterns', 'events/record-batches-and-corrections'],
    ['events/instances-and-locks', 'events/record-batches-and-corrections'],
    ['events/templates-and-settings', 'events/record-batches-and-corrections'],
    ['getting-started/navigation-and-saved-context', 'getting-started/access-and-navigation'],
    ['getting-started/ten-minute-first-session', 'getting-started/first-visit'],
    ['imports/apply-and-history', 'imports/row-statuses-and-decisions'],
    ['imports/providers-and-processing', 'imports/row-statuses-and-decisions'],
    ['imports/rollback-and-restore', 'imports/row-statuses-and-decisions'],
    ['imports/spreadsheet-and-structured-input', 'imports/row-statuses-and-decisions'],
    ['knowledge-hub/blocks-and-media', 'knowledge-hub/reading-sessions'],
    ['knowledge-hub/revisions-and-review', 'knowledge-hub/reading-sessions'],
    ['players/filters-and-columns', 'players/profile-and-history'],
    ['scopes-and-communities/cross-scope-visibility', 'scopes-and-communities/hierarchy-and-switching'],
    ['scopes-and-communities/membership-and-management', 'scopes-and-communities/hierarchy-and-switching'],
    ['subscriptions/grants-and-allocations', 'subscriptions/plans-and-effective-access'],
    ['subscriptions/quotas-and-limited-mode', 'subscriptions/plans-and-effective-access'],
    ['subscriptions/requests-and-payment', 'subscriptions/plans-and-effective-access'],
  ].map(([source, target], index) => ({
    product: 'kingshot-events', title: `Redirect: ${source}`, path: `/kingshot-events/${source.replace(/\/index$/, '')}`,
    navigationSection: 'Redirects', audience: 'Legacy visitors', experienceLevel: 'All levels', featureArea: 'Redirect',
    publicationStatus: 'redirect', sortOrder: 1200 + index, lastReviewedDate: '2026-08-01',
    file: `kingshot-events/${source}.md`, redirectTo: `/kingshot-events/${target}`
  }))
]
