// Generated from the reviewed comprehensive manual catalog.
export const manualPages = [
  {
    "product": "kingshot-events",
    "title": "Start Here",
    "path": "/kingshot-events/getting-started/",
    "navigationSection": "Getting Started",
    "audience": "All new users",
    "experienceLevel": "Beginner",
    "featureArea": "Getting Started",
    "publicationStatus": "published",
    "sortOrder": 200,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/getting-started/index.md"
  },
  {
    "product": "kingshot-events",
    "title": "A Ten-Minute First Session",
    "path": "/kingshot-events/getting-started/ten-minute-first-session",
    "navigationSection": "Getting Started",
    "audience": "Newly approved users",
    "experienceLevel": "Intermediate",
    "featureArea": "Getting Started",
    "publicationStatus": "published",
    "sortOrder": 201,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/getting-started/ten-minute-first-session.md"
  },
  {
    "product": "kingshot-events",
    "title": "Navigation and Saved Context",
    "path": "/kingshot-events/getting-started/navigation-and-saved-context",
    "navigationSection": "Getting Started",
    "audience": "All signed-in users",
    "experienceLevel": "Intermediate",
    "featureArea": "Getting Started",
    "publicationStatus": "published",
    "sortOrder": 202,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/getting-started/navigation-and-saved-context.md"
  },
  {
    "product": "kingshot-events",
    "title": "Accounts and Access",
    "path": "/kingshot-events/accounts-and-access/",
    "navigationSection": "Accounts and Access",
    "audience": "All users",
    "experienceLevel": "Beginner",
    "featureArea": "Accounts and Access",
    "publicationStatus": "published",
    "sortOrder": 203,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/accounts-and-access/index.md"
  },
  {
    "product": "kingshot-events",
    "title": "Registration and Approval",
    "path": "/kingshot-events/accounts-and-access/registration-and-approval",
    "navigationSection": "Accounts and Access",
    "audience": "New users and approvers",
    "experienceLevel": "Intermediate",
    "featureArea": "Accounts and Access",
    "publicationStatus": "published",
    "sortOrder": 204,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/accounts-and-access/registration-and-approval.md"
  },
  {
    "product": "kingshot-events",
    "title": "Password and Sign-In Security",
    "path": "/kingshot-events/accounts-and-access/password-and-security",
    "navigationSection": "Accounts and Access",
    "audience": "All account holders",
    "experienceLevel": "Intermediate",
    "featureArea": "Accounts and Access",
    "publicationStatus": "published",
    "sortOrder": 205,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/accounts-and-access/password-and-security.md"
  },
  {
    "product": "kingshot-events",
    "title": "Player Link Review",
    "path": "/kingshot-events/accounts-and-access/player-link-review",
    "navigationSection": "Accounts and Access",
    "audience": "Players and community managers",
    "experienceLevel": "Intermediate",
    "featureArea": "Accounts and Access",
    "publicationStatus": "published",
    "sortOrder": 206,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/accounts-and-access/player-link-review.md"
  },
  {
    "product": "kingshot-events",
    "title": "Multi-Role Access",
    "path": "/kingshot-events/accounts-and-access/multi-role-access",
    "navigationSection": "Accounts and Access",
    "audience": "Leaders with more than one responsibility",
    "experienceLevel": "Intermediate",
    "featureArea": "Accounts and Access",
    "publicationStatus": "published",
    "sortOrder": 207,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/accounts-and-access/multi-role-access.md"
  },
  {
    "product": "kingshot-events",
    "title": "Scopes and Communities",
    "path": "/kingshot-events/scopes-and-communities/",
    "navigationSection": "Scopes and Communities",
    "audience": "All signed-in users",
    "experienceLevel": "Beginner",
    "featureArea": "Scopes and Communities",
    "publicationStatus": "published",
    "sortOrder": 208,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/scopes-and-communities/index.md"
  },
  {
    "product": "kingshot-events",
    "title": "Hierarchy and Scope Switching",
    "path": "/kingshot-events/scopes-and-communities/hierarchy-and-switching",
    "navigationSection": "Scopes and Communities",
    "audience": "Members and managers",
    "experienceLevel": "Intermediate",
    "featureArea": "Scopes and Communities",
    "publicationStatus": "published",
    "sortOrder": 209,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/scopes-and-communities/hierarchy-and-switching.md"
  },
  {
    "product": "kingshot-events",
    "title": "Membership and Community Management",
    "path": "/kingshot-events/scopes-and-communities/membership-and-management",
    "navigationSection": "Scopes and Communities",
    "audience": "Alliance and kingdom leaders",
    "experienceLevel": "Intermediate",
    "featureArea": "Scopes and Communities",
    "publicationStatus": "published",
    "sortOrder": 210,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/scopes-and-communities/membership-and-management.md"
  },
  {
    "product": "kingshot-events",
    "title": "Cross-Scope Visibility",
    "path": "/kingshot-events/scopes-and-communities/cross-scope-visibility",
    "navigationSection": "Scopes and Communities",
    "audience": "Leaders and analytics viewers",
    "experienceLevel": "Intermediate",
    "featureArea": "Scopes and Communities",
    "publicationStatus": "published",
    "sortOrder": 211,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/scopes-and-communities/cross-scope-visibility.md"
  },
  {
    "product": "kingshot-events",
    "title": "Players Guide",
    "path": "/kingshot-events/players/",
    "navigationSection": "Players",
    "audience": "Players and roster managers",
    "experienceLevel": "Beginner",
    "featureArea": "Players",
    "publicationStatus": "published",
    "sortOrder": 212,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/players/index.md"
  },
  {
    "product": "kingshot-events",
    "title": "Directory Filters and Columns",
    "path": "/kingshot-events/players/filters-and-columns",
    "navigationSection": "Players",
    "audience": "Members and roster managers",
    "experienceLevel": "Intermediate",
    "featureArea": "Players",
    "publicationStatus": "published",
    "sortOrder": 213,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/players/filters-and-columns.md"
  },
  {
    "product": "kingshot-events",
    "title": "Profile, Attributes, and History",
    "path": "/kingshot-events/players/profile-and-history",
    "navigationSection": "Players",
    "audience": "Players and managers",
    "experienceLevel": "Intermediate",
    "featureArea": "Players",
    "publicationStatus": "published",
    "sortOrder": 214,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/players/profile-and-history.md"
  },
  {
    "product": "kingshot-events",
    "title": "Events and Results Guide",
    "path": "/kingshot-events/events/",
    "navigationSection": "Events and Results",
    "audience": "Participants and event managers",
    "experienceLevel": "Beginner",
    "featureArea": "Events and Results",
    "publicationStatus": "published",
    "sortOrder": 215,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/events/index.md"
  },
  {
    "product": "kingshot-events",
    "title": "Templates and Event Settings",
    "path": "/kingshot-events/events/templates-and-settings",
    "navigationSection": "Events and Results",
    "audience": "Event managers",
    "experienceLevel": "Intermediate",
    "featureArea": "Events and Results",
    "publicationStatus": "published",
    "sortOrder": 216,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/events/templates-and-settings.md"
  },
  {
    "product": "kingshot-events",
    "title": "Instances, Windows, and Locks",
    "path": "/kingshot-events/events/instances-and-locks",
    "navigationSection": "Events and Results",
    "audience": "Participants and event managers",
    "experienceLevel": "Intermediate",
    "featureArea": "Events and Results",
    "publicationStatus": "published",
    "sortOrder": 217,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/events/instances-and-locks.md"
  },
  {
    "product": "kingshot-events",
    "title": "Custom Events and Proposals",
    "path": "/kingshot-events/events/custom-events-and-proposals",
    "navigationSection": "Events and Results",
    "audience": "Community managers",
    "experienceLevel": "Intermediate",
    "featureArea": "Events and Results",
    "publicationStatus": "published",
    "sortOrder": 218,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/events/custom-events-and-proposals.md"
  },
  {
    "product": "kingshot-events",
    "title": "Record Batches and Corrections",
    "path": "/kingshot-events/events/record-batches-and-corrections",
    "navigationSection": "Events and Results",
    "audience": "Result contributors and reviewers",
    "experienceLevel": "Intermediate",
    "featureArea": "Events and Results",
    "publicationStatus": "published",
    "sortOrder": 219,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/events/record-batches-and-corrections.md"
  },
  {
    "product": "kingshot-events",
    "title": "Default Event Patterns",
    "path": "/kingshot-events/events/default-event-patterns",
    "navigationSection": "Events and Results",
    "audience": "Players and event managers",
    "experienceLevel": "Intermediate",
    "featureArea": "Events and Results",
    "publicationStatus": "published",
    "sortOrder": 220,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/events/default-event-patterns.md"
  },
  {
    "product": "kingshot-events",
    "title": "Imports and Data Entry Guide",
    "path": "/kingshot-events/imports/",
    "navigationSection": "Imports and Data Entry",
    "audience": "Contributors and reviewers",
    "experienceLevel": "Beginner",
    "featureArea": "Imports and Data Entry",
    "publicationStatus": "published",
    "sortOrder": 221,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/imports/index.md"
  },
  {
    "product": "kingshot-events",
    "title": "Providers and Processing",
    "path": "/kingshot-events/imports/providers-and-processing",
    "navigationSection": "Imports and Data Entry",
    "audience": "Import contributors",
    "experienceLevel": "Intermediate",
    "featureArea": "Imports and Data Entry",
    "publicationStatus": "published",
    "sortOrder": 222,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/imports/providers-and-processing.md"
  },
  {
    "product": "kingshot-events",
    "title": "Row Statuses and Decisions",
    "path": "/kingshot-events/imports/row-statuses-and-decisions",
    "navigationSection": "Imports and Data Entry",
    "audience": "Import reviewers",
    "experienceLevel": "Intermediate",
    "featureArea": "Imports and Data Entry",
    "publicationStatus": "published",
    "sortOrder": 223,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/imports/row-statuses-and-decisions.md"
  },
  {
    "product": "kingshot-events",
    "title": "Apply and Import History",
    "path": "/kingshot-events/imports/apply-and-history",
    "navigationSection": "Imports and Data Entry",
    "audience": "Contributors and managers",
    "experienceLevel": "Intermediate",
    "featureArea": "Imports and Data Entry",
    "publicationStatus": "published",
    "sortOrder": 224,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/imports/apply-and-history.md"
  },
  {
    "product": "kingshot-events",
    "title": "Rollback and Restore",
    "path": "/kingshot-events/imports/rollback-and-restore",
    "navigationSection": "Imports and Data Entry",
    "audience": "Managers and restore reviewers",
    "experienceLevel": "Intermediate",
    "featureArea": "Imports and Data Entry",
    "publicationStatus": "published",
    "sortOrder": 225,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/imports/rollback-and-restore.md"
  },
  {
    "product": "kingshot-events",
    "title": "Spreadsheet and Structured Input",
    "path": "/kingshot-events/imports/spreadsheet-and-structured-input",
    "navigationSection": "Imports and Data Entry",
    "audience": "Experienced contributors",
    "experienceLevel": "Intermediate",
    "featureArea": "Imports and Data Entry",
    "publicationStatus": "published",
    "sortOrder": 226,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/imports/spreadsheet-and-structured-input.md"
  },
  {
    "product": "kingshot-events",
    "title": "Analytics and Rewards Guide",
    "path": "/kingshot-events/analytics/",
    "navigationSection": "Analytics and Rewards",
    "audience": "Players, leaders, and reward managers",
    "experienceLevel": "Beginner",
    "featureArea": "Analytics and Rewards",
    "publicationStatus": "published",
    "sortOrder": 227,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/analytics/index.md"
  },
  {
    "product": "kingshot-events",
    "title": "Filters and Recalculation",
    "path": "/kingshot-events/analytics/filters-and-recalculation",
    "navigationSection": "Analytics and Rewards",
    "audience": "Analytics viewers",
    "experienceLevel": "Intermediate",
    "featureArea": "Analytics and Rewards",
    "publicationStatus": "published",
    "sortOrder": 228,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/analytics/filters-and-recalculation.md"
  },
  {
    "product": "kingshot-events",
    "title": "Recommendations and Missing Data",
    "path": "/kingshot-events/analytics/recommendations-and-missing-data",
    "navigationSection": "Analytics and Rewards",
    "audience": "Leaders and analysts",
    "experienceLevel": "Intermediate",
    "featureArea": "Analytics and Rewards",
    "publicationStatus": "published",
    "sortOrder": 229,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/analytics/recommendations-and-missing-data.md"
  },
  {
    "product": "kingshot-events",
    "title": "Reward Rules and Outcomes",
    "path": "/kingshot-events/analytics/reward-rules",
    "navigationSection": "Analytics and Rewards",
    "audience": "Reward managers and players",
    "experienceLevel": "Intermediate",
    "featureArea": "Analytics and Rewards",
    "publicationStatus": "published",
    "sortOrder": 230,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/analytics/reward-rules.md"
  },
  {
    "product": "kingshot-events",
    "title": "Resources, Eligibility, and Capacity",
    "path": "/kingshot-events/castle-positions/resources-and-eligibility",
    "navigationSection": "Castle Positions",
    "audience": "Applicants and position managers",
    "experienceLevel": "Intermediate",
    "featureArea": "Castle Positions",
    "publicationStatus": "published",
    "sortOrder": 231,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/castle-positions/resources-and-eligibility.md"
  },
  {
    "product": "kingshot-events",
    "title": "Planner Controls and Conflict Resolution",
    "path": "/kingshot-events/castle-positions/planner-controls",
    "navigationSection": "Castle Positions",
    "audience": "Kings and Ministers of Justice",
    "experienceLevel": "Intermediate",
    "featureArea": "Castle Positions",
    "publicationStatus": "published",
    "sortOrder": 232,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/castle-positions/planner-controls.md"
  },
  {
    "product": "kingshot-events",
    "title": "Notifications and Published Versions",
    "path": "/kingshot-events/castle-positions/notifications-and-versions",
    "navigationSection": "Castle Positions",
    "audience": "Applicants and schedule managers",
    "experienceLevel": "Intermediate",
    "featureArea": "Castle Positions",
    "publicationStatus": "published",
    "sortOrder": 233,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/castle-positions/notifications-and-versions.md"
  },
  {
    "product": "kingshot-events",
    "title": "Knowledge Hub Guide",
    "path": "/kingshot-events/knowledge-hub/",
    "navigationSection": "Knowledge Hub",
    "audience": "Readers, authors, and reviewers",
    "experienceLevel": "Beginner",
    "featureArea": "Knowledge Hub",
    "publicationStatus": "published",
    "sortOrder": 234,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/knowledge-hub/index.md"
  },
  {
    "product": "kingshot-events",
    "title": "Blocks, Media, and Structured Content",
    "path": "/kingshot-events/knowledge-hub/blocks-and-media",
    "navigationSection": "Knowledge Hub",
    "audience": "Knowledge authors",
    "experienceLevel": "Intermediate",
    "featureArea": "Knowledge Hub",
    "publicationStatus": "published",
    "sortOrder": 235,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/knowledge-hub/blocks-and-media.md"
  },
  {
    "product": "kingshot-events",
    "title": "Revisions and Review",
    "path": "/kingshot-events/knowledge-hub/revisions-and-review",
    "navigationSection": "Knowledge Hub",
    "audience": "Authors and reviewers",
    "experienceLevel": "Intermediate",
    "featureArea": "Knowledge Hub",
    "publicationStatus": "published",
    "sortOrder": 236,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/knowledge-hub/revisions-and-review.md"
  },
  {
    "product": "kingshot-events",
    "title": "Reading Sessions",
    "path": "/kingshot-events/knowledge-hub/reading-sessions",
    "navigationSection": "Knowledge Hub",
    "audience": "Session managers and readers",
    "experienceLevel": "Intermediate",
    "featureArea": "Knowledge Hub",
    "publicationStatus": "published",
    "sortOrder": 237,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/knowledge-hub/reading-sessions.md"
  },
  {
    "product": "kingshot-events",
    "title": "Profiles, Assumptions, and Autosave",
    "path": "/kingshot-events/lab/profiles-and-autosave",
    "navigationSection": "Simulations and Optimizations",
    "audience": "Lab users",
    "experienceLevel": "Intermediate",
    "featureArea": "Simulations and Optimizations",
    "publicationStatus": "published",
    "sortOrder": 238,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/lab/profiles-and-autosave.md"
  },
  {
    "product": "kingshot-events",
    "title": "Hero Gear Planning",
    "path": "/kingshot-events/lab/hero-gear",
    "navigationSection": "Simulations and Optimizations",
    "audience": "Players planning hero upgrades",
    "experienceLevel": "Intermediate",
    "featureArea": "Simulations and Optimizations",
    "publicationStatus": "published",
    "sortOrder": 239,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/lab/hero-gear.md"
  },
  {
    "product": "kingshot-events",
    "title": "Governor Gear Planning",
    "path": "/kingshot-events/lab/governor-gear",
    "navigationSection": "Simulations and Optimizations",
    "audience": "Players planning governor upgrades",
    "experienceLevel": "Intermediate",
    "featureArea": "Simulations and Optimizations",
    "publicationStatus": "published",
    "sortOrder": 240,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/lab/governor-gear.md"
  },
  {
    "product": "kingshot-events",
    "title": "Charm Planning",
    "path": "/kingshot-events/lab/charms",
    "navigationSection": "Simulations and Optimizations",
    "audience": "Players planning charm upgrades",
    "experienceLevel": "Intermediate",
    "featureArea": "Simulations and Optimizations",
    "publicationStatus": "published",
    "sortOrder": 241,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/lab/charms.md"
  },
  {
    "product": "kingshot-events",
    "title": "Bear Trap Planning",
    "path": "/kingshot-events/lab/bear-trap",
    "navigationSection": "Simulations and Optimizations",
    "audience": "Alliance rally planners",
    "experienceLevel": "Intermediate",
    "featureArea": "Simulations and Optimizations",
    "publicationStatus": "published",
    "sortOrder": 242,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/lab/bear-trap.md"
  },
  {
    "product": "kingshot-events",
    "title": "Plans and Effective Access",
    "path": "/kingshot-events/subscriptions/plans-and-effective-access",
    "navigationSection": "Subscriptions and Usage",
    "audience": "Members and community owners",
    "experienceLevel": "Intermediate",
    "featureArea": "Subscriptions and Usage",
    "publicationStatus": "published",
    "sortOrder": 243,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/subscriptions/plans-and-effective-access.md"
  },
  {
    "product": "kingshot-events",
    "title": "Grants and Allocations",
    "path": "/kingshot-events/subscriptions/grants-and-allocations",
    "navigationSection": "Subscriptions and Usage",
    "audience": "Kingdom and alliance owners",
    "experienceLevel": "Intermediate",
    "featureArea": "Subscriptions and Usage",
    "publicationStatus": "published",
    "sortOrder": 244,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/subscriptions/grants-and-allocations.md"
  },
  {
    "product": "kingshot-events",
    "title": "Requests and Payment States",
    "path": "/kingshot-events/subscriptions/requests-and-payment",
    "navigationSection": "Subscriptions and Usage",
    "audience": "Requesters and community owners",
    "experienceLevel": "Intermediate",
    "featureArea": "Subscriptions and Usage",
    "publicationStatus": "published",
    "sortOrder": 245,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/subscriptions/requests-and-payment.md"
  },
  {
    "product": "kingshot-events",
    "title": "Quotas and Limited Mode",
    "path": "/kingshot-events/subscriptions/quotas-and-limited-mode",
    "navigationSection": "Subscriptions and Usage",
    "audience": "All users of limited features",
    "experienceLevel": "Intermediate",
    "featureArea": "Subscriptions and Usage",
    "publicationStatus": "published",
    "sortOrder": 246,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/subscriptions/quotas-and-limited-mode.md"
  },
  {
    "product": "kingshot-events",
    "title": "Notifications and Reports",
    "path": "/kingshot-events/lifecycles/notifications-and-reports",
    "navigationSection": "Platform Lifecycles",
    "audience": "All signed-in users",
    "experienceLevel": "Intermediate",
    "featureArea": "Platform Lifecycles",
    "publicationStatus": "published",
    "sortOrder": 247,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/lifecycles/notifications-and-reports.md"
  },
  {
    "product": "kingshot-events",
    "title": "Recycle Bin and Restore Requests",
    "path": "/kingshot-events/lifecycles/recycle-bin-and-restore-requests",
    "navigationSection": "Platform Lifecycles",
    "audience": "Managers and restore reviewers",
    "experienceLevel": "Intermediate",
    "featureArea": "Platform Lifecycles",
    "publicationStatus": "published",
    "sortOrder": 248,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/lifecycles/recycle-bin-and-restore-requests.md"
  },
  {
    "product": "kingshot-events",
    "title": "Problem Catalog",
    "path": "/kingshot-events/troubleshooting/",
    "navigationSection": "Troubleshooting",
    "audience": "All users",
    "experienceLevel": "Beginner",
    "featureArea": "Troubleshooting",
    "publicationStatus": "published",
    "sortOrder": 249,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/troubleshooting/index.md"
  }
]
