import { manualPages } from './manual-pages.mts'

// Authoritative publication registry. Navigation, search inclusion, route checks, and sitemap output derive from this list.
export const publicationManifest = [
  ...manualPages,
  {
    "product": "ralyvora-docs",
    "title": "Ralyvora Docs",
    "path": "/",
    "navigationSection": "Portal",
    "audience": "All visitors",
    "experienceLevel": "Beginner",
    "featureArea": "Portal",
    "publicationStatus": "published",
    "sortOrder": 0,
    "lastReviewedDate": "2026-08-01",
    "file": "index.md"
  },
  {
    "product": "kingshot-events",
    "title": "Kingshot Events",
    "path": "/kingshot-events/",
    "navigationSection": "Overview",
    "audience": "All Kingshot Events users",
    "experienceLevel": "Beginner",
    "featureArea": "Product overview",
    "publicationStatus": "published",
    "sortOrder": 10,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/index.md"
  },
  {
    "product": "kingshot-events",
    "title": "Problems Kingshot Events Solves",
    "path": "/kingshot-events/overview/problems-solved",
    "navigationSection": "Overview",
    "audience": "All users",
    "experienceLevel": "Beginner",
    "featureArea": "Product overview",
    "publicationStatus": "published",
    "sortOrder": 11,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/overview/problems-solved.md"
  },
  {
    "product": "kingshot-events",
    "title": "How the Platform Fits Together",
    "path": "/kingshot-events/overview/platform-model",
    "navigationSection": "Overview",
    "audience": "All users",
    "experienceLevel": "Beginner",
    "featureArea": "Scopes and records",
    "publicationStatus": "published",
    "sortOrder": 12,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/overview/platform-model.md"
  },
  {
    "product": "kingshot-events",
    "title": "Product Terminology",
    "path": "/kingshot-events/overview/terminology",
    "navigationSection": "Overview",
    "audience": "All users",
    "experienceLevel": "Beginner",
    "featureArea": "Terminology",
    "publicationStatus": "published",
    "sortOrder": 13,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/overview/terminology.md"
  },
  {
    "product": "kingshot-events",
    "title": "Feature Availability",
    "path": "/kingshot-events/overview/feature-availability",
    "navigationSection": "Overview",
    "audience": "All users",
    "experienceLevel": "Beginner",
    "featureArea": "Availability",
    "publicationStatus": "published",
    "sortOrder": 14,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/overview/feature-availability.md"
  },
  {
    "product": "kingshot-events",
    "title": "Your First Visit, Registration, and Login",
    "path": "/kingshot-events/getting-started/first-visit",
    "navigationSection": "Getting Started",
    "audience": "New users",
    "experienceLevel": "Beginner",
    "featureArea": "Account access",
    "publicationStatus": "published",
    "sortOrder": 20,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/getting-started/first-visit.md"
  },
  {
    "product": "kingshot-events",
    "title": "Account, Profile, and Player Link",
    "path": "/kingshot-events/getting-started/account-and-profile",
    "navigationSection": "Getting Started",
    "audience": "All signed-in users",
    "experienceLevel": "Beginner",
    "featureArea": "Accounts and profiles",
    "publicationStatus": "published",
    "sortOrder": 21,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/getting-started/account-and-profile.md"
  },
  {
    "product": "kingshot-events",
    "title": "Choosing Scope and Understanding Access",
    "path": "/kingshot-events/getting-started/access-and-navigation",
    "navigationSection": "Getting Started",
    "audience": "All signed-in users",
    "experienceLevel": "Beginner",
    "featureArea": "Scope and access",
    "publicationStatus": "published",
    "sortOrder": 22,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/getting-started/access-and-navigation.md"
  },
  {
    "product": "kingshot-events",
    "title": "Player Directory and Profiles",
    "path": "/kingshot-events/players/directory-and-profiles",
    "navigationSection": "Players",
    "audience": "Members and managers",
    "experienceLevel": "Intermediate",
    "featureArea": "Players",
    "publicationStatus": "published",
    "sortOrder": 30,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/players/directory-and-profiles.md"
  },
  {
    "product": "kingshot-events",
    "title": "Adding and Updating Players",
    "path": "/kingshot-events/players/manage-players",
    "navigationSection": "Players",
    "audience": "Alliance and kingdom managers",
    "experienceLevel": "Intermediate",
    "featureArea": "Players",
    "publicationStatus": "published",
    "sortOrder": 31,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/players/manage-players.md"
  },
  {
    "product": "kingshot-events",
    "title": "Player Linking and Synchronization",
    "path": "/kingshot-events/players/linking-and-sync",
    "navigationSection": "Players",
    "audience": "Players and managers",
    "experienceLevel": "Intermediate",
    "featureArea": "Player linking",
    "publicationStatus": "published",
    "sortOrder": 32,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/players/linking-and-sync.md"
  },
  {
    "product": "kingshot-events",
    "title": "Activity, Attributes, Removal, and Restore",
    "path": "/kingshot-events/players/lifecycle",
    "navigationSection": "Players",
    "audience": "Players and managers",
    "experienceLevel": "Intermediate",
    "featureArea": "Player lifecycle",
    "publicationStatus": "published",
    "sortOrder": 33,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/players/lifecycle.md"
  },
  {
    "product": "kingshot-events",
    "title": "How Scopes Work",
    "path": "/kingshot-events/kingdoms-and-alliances/scopes",
    "navigationSection": "Kingdoms and Alliances",
    "audience": "All signed-in users",
    "experienceLevel": "Intermediate",
    "featureArea": "Scopes",
    "publicationStatus": "published",
    "sortOrder": 40,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/kingdoms-and-alliances/scopes.md"
  },
  {
    "product": "kingshot-events",
    "title": "Working Inside an Alliance",
    "path": "/kingshot-events/kingdoms-and-alliances/alliance-work",
    "navigationSection": "Kingdoms and Alliances",
    "audience": "Alliance leaders and co-leaders",
    "experienceLevel": "Intermediate",
    "featureArea": "Alliance management",
    "publicationStatus": "published",
    "sortOrder": 41,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/kingdoms-and-alliances/alliance-work.md"
  },
  {
    "product": "kingshot-events",
    "title": "Working Inside a Kingdom",
    "path": "/kingshot-events/kingdoms-and-alliances/kingdom-work",
    "navigationSection": "Kingdoms and Alliances",
    "audience": "Kings, kingdom managers, and Ministers of Justice",
    "experienceLevel": "Intermediate",
    "featureArea": "Kingdom management",
    "publicationStatus": "published",
    "sortOrder": 42,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/kingdoms-and-alliances/kingdom-work.md"
  },
  {
    "product": "kingshot-events",
    "title": "Event Templates, Instances, and Results",
    "path": "/kingshot-events/events/overview",
    "navigationSection": "Events and Results",
    "audience": "Players and managers",
    "experienceLevel": "Intermediate",
    "featureArea": "Events",
    "publicationStatus": "published",
    "sortOrder": 50,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/events/overview.md"
  },
  {
    "product": "kingshot-events",
    "title": "Participation, Scores, Stages, and Cumulative Events",
    "path": "/kingshot-events/events/participation-and-scores",
    "navigationSection": "Events and Results",
    "audience": "Contributors and managers",
    "experienceLevel": "Intermediate",
    "featureArea": "Event results",
    "publicationStatus": "published",
    "sortOrder": 51,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/events/participation-and-scores.md"
  },
  {
    "product": "kingshot-events",
    "title": "Entering Results Manually",
    "path": "/kingshot-events/events/manual-entry",
    "navigationSection": "Events and Results",
    "audience": "Authorized contributors",
    "experienceLevel": "Intermediate",
    "featureArea": "Manual input",
    "publicationStatus": "published",
    "sortOrder": 52,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/events/manual-entry.md"
  },
  {
    "product": "kingshot-events",
    "title": "Reviewing Results and Event History",
    "path": "/kingshot-events/events/review-and-history",
    "navigationSection": "Events and Results",
    "audience": "Players and managers",
    "experienceLevel": "Intermediate",
    "featureArea": "Event review",
    "publicationStatus": "published",
    "sortOrder": 53,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/events/review-and-history.md"
  },
  {
    "product": "kingshot-events",
    "title": "Event-Specific Behavior and Template Changes",
    "path": "/kingshot-events/events/event-specific-behavior",
    "navigationSection": "Events and Results",
    "audience": "Players and managers",
    "experienceLevel": "Intermediate",
    "featureArea": "Events",
    "publicationStatus": "published",
    "sortOrder": 54,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/events/event-specific-behavior.md"
  },
  {
    "product": "kingshot-events",
    "title": "Screenshot Import",
    "path": "/kingshot-events/imports/screenshot-import",
    "navigationSection": "Imports and Data Entry",
    "audience": "Authorized contributors and managers",
    "experienceLevel": "Intermediate",
    "featureArea": "Imports",
    "publicationStatus": "published",
    "sortOrder": 60,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/imports/screenshot-import.md"
  },
  {
    "product": "kingshot-events",
    "title": "Reviewing and Applying Imported Data",
    "path": "/kingshot-events/imports/review-imported-data",
    "navigationSection": "Imports and Data Entry",
    "audience": "Contributors and alliance managers",
    "experienceLevel": "Intermediate",
    "featureArea": "Import review",
    "publicationStatus": "published",
    "sortOrder": 61,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/imports/review-imported-data.md"
  },
  {
    "product": "kingshot-events",
    "title": "Duplicate, Date, Overwrite, and Restore Rules",
    "path": "/kingshot-events/imports/data-rules",
    "navigationSection": "Imports and Data Entry",
    "audience": "Contributors and managers",
    "experienceLevel": "Intermediate",
    "featureArea": "Data integrity",
    "publicationStatus": "published",
    "sortOrder": 62,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/imports/data-rules.md"
  },
  {
    "product": "kingshot-events",
    "title": "Import Troubleshooting",
    "path": "/kingshot-events/imports/import-troubleshooting",
    "navigationSection": "Imports and Data Entry",
    "audience": "Import contributors",
    "experienceLevel": "Intermediate",
    "featureArea": "Imports",
    "publicationStatus": "published",
    "sortOrder": 63,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/imports/import-troubleshooting.md"
  },
  {
    "product": "kingshot-events",
    "title": "War Room Analytics Overview",
    "path": "/kingshot-events/analytics/activity-and-results",
    "navigationSection": "Analytics and Rewards",
    "audience": "Players and managers",
    "experienceLevel": "Intermediate",
    "featureArea": "Analytics",
    "publicationStatus": "published",
    "sortOrder": 70,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/analytics/activity-and-results.md"
  },
  {
    "product": "kingshot-events",
    "title": "Kingdom Analytics",
    "path": "/kingshot-events/analytics/kingdom",
    "navigationSection": "Analytics and Rewards",
    "audience": "Kings, kingdom managers, and granted analytics viewers",
    "experienceLevel": "Intermediate",
    "featureArea": "Analytics",
    "publicationStatus": "published",
    "sortOrder": 71,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/analytics/kingdom.md"
  },
  {
    "product": "kingshot-events",
    "title": "Alliance Analytics",
    "path": "/kingshot-events/analytics/alliance",
    "navigationSection": "Analytics and Rewards",
    "audience": "Alliance and kingdom analytics viewers",
    "experienceLevel": "Intermediate",
    "featureArea": "Analytics",
    "publicationStatus": "published",
    "sortOrder": 72,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/analytics/alliance.md"
  },
  {
    "product": "kingshot-events",
    "title": "Player Cross-Event Analytics",
    "path": "/kingshot-events/analytics/player",
    "navigationSection": "Analytics and Rewards",
    "audience": "Players and analytics viewers",
    "experienceLevel": "Intermediate",
    "featureArea": "Analytics",
    "publicationStatus": "published",
    "sortOrder": 73,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/analytics/player.md"
  },
  {
    "product": "kingshot-events",
    "title": "Custom Analytics",
    "path": "/kingshot-events/analytics/custom",
    "navigationSection": "Analytics and Rewards",
    "audience": "Premium analytics viewers",
    "experienceLevel": "Advanced",
    "featureArea": "Analytics",
    "publicationStatus": "published",
    "sortOrder": 74,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/analytics/custom.md"
  },
  {
    "product": "kingshot-events",
    "title": "Analytics Sharing, Scope, and Troubleshooting",
    "path": "/kingshot-events/analytics/sharing-and-troubleshooting",
    "navigationSection": "Analytics and Rewards",
    "audience": "Analytics viewers and managers",
    "experienceLevel": "Intermediate",
    "featureArea": "Analytics access",
    "publicationStatus": "published",
    "sortOrder": 75,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/analytics/sharing-and-troubleshooting.md"
  },
  {
    "product": "kingshot-events",
    "title": "Reward Eligibility and Statuses",
    "path": "/kingshot-events/analytics/rewards-and-statuses",
    "navigationSection": "Analytics and Rewards",
    "audience": "Players and reward managers",
    "experienceLevel": "Intermediate",
    "featureArea": "Rewards",
    "publicationStatus": "published",
    "sortOrder": 76,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/analytics/rewards-and-statuses.md"
  },
  {
    "product": "kingshot-events",
    "title": "Castle Positions Overview",
    "path": "/kingshot-events/castle-positions/",
    "navigationSection": "Castle Positions",
    "audience": "Players and kingdom managers",
    "experienceLevel": "Intermediate",
    "featureArea": "Castle Positions",
    "publicationStatus": "published",
    "sortOrder": 80,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/castle-positions/index.md"
  },
  {
    "product": "kingshot-events",
    "title": "Castle Position Applicant Guide",
    "path": "/kingshot-events/castle-positions/applicant-guide",
    "navigationSection": "Castle Positions",
    "audience": "Players",
    "experienceLevel": "Intermediate",
    "featureArea": "Castle Position applications",
    "publicationStatus": "published",
    "sortOrder": 81,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/castle-positions/applicant-guide.md"
  },
  {
    "product": "kingshot-events",
    "title": "Castle Position Review Workflow",
    "path": "/kingshot-events/castle-positions/review-workflow",
    "navigationSection": "Castle Positions",
    "audience": "Kings, kingdom managers, and Ministers of Justice",
    "experienceLevel": "Intermediate",
    "featureArea": "Castle Position review",
    "publicationStatus": "published",
    "sortOrder": 82,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/castle-positions/review-workflow.md"
  },
  {
    "product": "kingshot-events",
    "title": "Planning, Scheduling, and Publishing",
    "path": "/kingshot-events/castle-positions/planning-and-publishing",
    "navigationSection": "Castle Positions",
    "audience": "Authorized kingdom managers",
    "experienceLevel": "Intermediate",
    "featureArea": "Castle Position scheduling",
    "publicationStatus": "published",
    "sortOrder": 83,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/castle-positions/planning-and-publishing.md"
  },
  {
    "product": "kingshot-events",
    "title": "Castle Position Statuses, Changes, and Notifications",
    "path": "/kingshot-events/castle-positions/statuses-and-changes",
    "navigationSection": "Castle Positions",
    "audience": "Applicants and managers",
    "experienceLevel": "Intermediate",
    "featureArea": "Castle Position statuses",
    "publicationStatus": "published",
    "sortOrder": 84,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/castle-positions/statuses-and-changes.md"
  },
  {
    "product": "kingshot-events",
    "title": "Reading and Finding Knowledge",
    "path": "/kingshot-events/knowledge-hub/reading-and-finding",
    "navigationSection": "Knowledge Hub",
    "audience": "Knowledge readers",
    "experienceLevel": "Intermediate",
    "featureArea": "Knowledge Hub",
    "publicationStatus": "published",
    "sortOrder": 90,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/knowledge-hub/reading-and-finding.md"
  },
  {
    "product": "kingshot-events",
    "title": "Knowledge Access and Browser Translation Assistance",
    "path": "/kingshot-events/knowledge-hub/access-and-translation",
    "navigationSection": "Knowledge Hub",
    "audience": "Knowledge readers",
    "experienceLevel": "Intermediate",
    "featureArea": "Knowledge access",
    "publicationStatus": "published",
    "sortOrder": 91,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/knowledge-hub/access-and-translation.md"
  },
  {
    "product": "kingshot-events",
    "title": "Reading Verification",
    "path": "/kingshot-events/knowledge-hub/reading-verification",
    "navigationSection": "Knowledge Hub",
    "audience": "Readers and session managers",
    "experienceLevel": "Intermediate",
    "featureArea": "Reading Verification",
    "publicationStatus": "published",
    "sortOrder": 92,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/knowledge-hub/reading-verification.md"
  },
  {
    "product": "kingshot-events",
    "title": "Knowledge Authoring, Imports, Review, and Publication",
    "path": "/kingshot-events/knowledge-hub/authoring-and-publication",
    "navigationSection": "Knowledge Hub",
    "audience": "Knowledge authors and reviewers",
    "experienceLevel": "Intermediate",
    "featureArea": "Knowledge authoring",
    "publicationStatus": "published",
    "sortOrder": 93,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/knowledge-hub/authoring-and-publication.md"
  },
  {
    "product": "kingshot-events",
    "title": "Lab Overview and Profiles",
    "path": "/kingshot-events/lab/",
    "navigationSection": "Simulations and Optimizations",
    "audience": "All Lab users",
    "experienceLevel": "Intermediate",
    "featureArea": "Lab",
    "publicationStatus": "published",
    "sortOrder": 100,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/lab/index.md"
  },
  {
    "product": "kingshot-events",
    "title": "Account Progress Planner",
    "path": "/kingshot-events/lab/account-progress-planner",
    "navigationSection": "Simulations and Optimizations",
    "audience": "Lab users",
    "experienceLevel": "Intermediate",
    "featureArea": "Account Progress Planner",
    "publicationStatus": "published",
    "sortOrder": 101,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/lab/account-progress-planner.md"
  },
  {
    "product": "kingshot-events",
    "title": "Hero Gear, Governor Gear, and Charms",
    "path": "/kingshot-events/lab/gear-and-charms",
    "navigationSection": "Simulations and Optimizations",
    "audience": "Lab users",
    "experienceLevel": "Intermediate",
    "featureArea": "Progression optimizers",
    "publicationStatus": "published",
    "sortOrder": 102,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/lab/gear-and-charms.md"
  },
  {
    "product": "kingshot-events",
    "title": "Bear Trap, Rally, and Battle Simulators",
    "path": "/kingshot-events/lab/bear-rally-battle",
    "navigationSection": "Simulations and Optimizations",
    "audience": "Lab users",
    "experienceLevel": "Intermediate",
    "featureArea": "Combat simulators",
    "publicationStatus": "published",
    "sortOrder": 103,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/lab/bear-rally-battle.md"
  },
  {
    "product": "kingshot-events",
    "title": "Interpreting Lab Results and Limitations",
    "path": "/kingshot-events/lab/interpreting-results",
    "navigationSection": "Simulations and Optimizations",
    "audience": "All Lab users",
    "experienceLevel": "Intermediate",
    "featureArea": "Lab results",
    "publicationStatus": "published",
    "sortOrder": 104,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/lab/interpreting-results.md"
  },
  {
    "product": "kingshot-events",
    "title": "Subscriptions, Requests, and Kingdom Grants",
    "path": "/kingshot-events/subscriptions/",
    "navigationSection": "Subscriptions",
    "audience": "Members and community managers",
    "experienceLevel": "Intermediate",
    "featureArea": "Subscriptions",
    "publicationStatus": "published",
    "sortOrder": 110,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/subscriptions/index.md"
  },
  {
    "product": "kingshot-events",
    "title": "Subscription Access, Scope, and Usage",
    "path": "/kingshot-events/subscriptions/access-and-usage",
    "navigationSection": "Subscriptions",
    "audience": "Members and subscription managers",
    "experienceLevel": "Intermediate",
    "featureArea": "Subscription access",
    "publicationStatus": "published",
    "sortOrder": 111,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/subscriptions/access-and-usage.md"
  },
  {
    "product": "kingshot-events",
    "title": "Subscription Troubleshooting",
    "path": "/kingshot-events/subscriptions/troubleshooting",
    "navigationSection": "Subscriptions",
    "audience": "Members and managers",
    "experienceLevel": "Intermediate",
    "featureArea": "Subscriptions",
    "publicationStatus": "published",
    "sortOrder": 112,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/subscriptions/troubleshooting.md"
  },
  {
    "product": "kingshot-events",
    "title": "Player or Alliance Member",
    "path": "/kingshot-events/role-journeys/player-or-member",
    "navigationSection": "Role Journeys",
    "audience": "Player or Alliance Member",
    "experienceLevel": "Beginner",
    "featureArea": "Role journey",
    "publicationStatus": "published",
    "sortOrder": 120,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/role-journeys/player-or-member.md"
  },
  {
    "product": "kingshot-events",
    "title": "Alliance Leader or Co-leader",
    "path": "/kingshot-events/role-journeys/alliance-leader",
    "navigationSection": "Role Journeys",
    "audience": "Alliance Leader or Co-leader",
    "experienceLevel": "Beginner",
    "featureArea": "Role journey",
    "publicationStatus": "published",
    "sortOrder": 121,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/role-journeys/alliance-leader.md"
  },
  {
    "product": "kingshot-events",
    "title": "King or Kingdom Manager",
    "path": "/kingshot-events/role-journeys/kingdom-manager",
    "navigationSection": "Role Journeys",
    "audience": "King or Kingdom Manager",
    "experienceLevel": "Beginner",
    "featureArea": "Role journey",
    "publicationStatus": "published",
    "sortOrder": 122,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/role-journeys/kingdom-manager.md"
  },
  {
    "product": "kingshot-events",
    "title": "Minister of Justice",
    "path": "/kingshot-events/role-journeys/minister-of-justice",
    "navigationSection": "Role Journeys",
    "audience": "Minister of Justice",
    "experienceLevel": "Beginner",
    "featureArea": "Role journey",
    "publicationStatus": "published",
    "sortOrder": 123,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/role-journeys/minister-of-justice.md"
  },
  {
    "product": "kingshot-events",
    "title": "Knowledge Author",
    "path": "/kingshot-events/role-journeys/knowledge-author",
    "navigationSection": "Role Journeys",
    "audience": "Knowledge Author",
    "experienceLevel": "Beginner",
    "featureArea": "Role journey",
    "publicationStatus": "published",
    "sortOrder": 124,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/role-journeys/knowledge-author.md"
  },
  {
    "product": "kingshot-events",
    "title": "Access Problems",
    "path": "/kingshot-events/troubleshooting/access-problems",
    "navigationSection": "Troubleshooting",
    "audience": "All affected users",
    "experienceLevel": "Beginner",
    "featureArea": "Troubleshooting",
    "publicationStatus": "published",
    "sortOrder": 130,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/troubleshooting/access-problems.md"
  },
  {
    "product": "kingshot-events",
    "title": "Data and Save Problems",
    "path": "/kingshot-events/troubleshooting/data-and-save-problems",
    "navigationSection": "Troubleshooting",
    "audience": "All affected users",
    "experienceLevel": "Beginner",
    "featureArea": "Troubleshooting",
    "publicationStatus": "published",
    "sortOrder": 131,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/troubleshooting/data-and-save-problems.md"
  },
  {
    "product": "kingshot-events",
    "title": "Event and Analytics Problems",
    "path": "/kingshot-events/troubleshooting/event-problems",
    "navigationSection": "Troubleshooting",
    "audience": "All affected users",
    "experienceLevel": "Beginner",
    "featureArea": "Troubleshooting",
    "publicationStatus": "published",
    "sortOrder": 132,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/troubleshooting/event-problems.md"
  },
  {
    "product": "kingshot-events",
    "title": "Import Problems",
    "path": "/kingshot-events/troubleshooting/import-problems",
    "navigationSection": "Troubleshooting",
    "audience": "All affected users",
    "experienceLevel": "Beginner",
    "featureArea": "Troubleshooting",
    "publicationStatus": "published",
    "sortOrder": 133,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/troubleshooting/import-problems.md"
  },
  {
    "product": "kingshot-events",
    "title": "Castle Position Problems",
    "path": "/kingshot-events/troubleshooting/castle-position-problems",
    "navigationSection": "Troubleshooting",
    "audience": "All affected users",
    "experienceLevel": "Beginner",
    "featureArea": "Troubleshooting",
    "publicationStatus": "published",
    "sortOrder": 134,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/troubleshooting/castle-position-problems.md"
  },
  {
    "product": "kingshot-events",
    "title": "Knowledge Problems",
    "path": "/kingshot-events/troubleshooting/knowledge-problems",
    "navigationSection": "Troubleshooting",
    "audience": "All affected users",
    "experienceLevel": "Beginner",
    "featureArea": "Troubleshooting",
    "publicationStatus": "published",
    "sortOrder": 135,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/troubleshooting/knowledge-problems.md"
  },
  {
    "product": "kingshot-events",
    "title": "Simulator and Optimizer Problems",
    "path": "/kingshot-events/troubleshooting/simulator-problems",
    "navigationSection": "Troubleshooting",
    "audience": "All affected users",
    "experienceLevel": "Beginner",
    "featureArea": "Troubleshooting",
    "publicationStatus": "published",
    "sortOrder": 136,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/troubleshooting/simulator-problems.md"
  },
  {
    "product": "kingshot-events",
    "title": "User-facing Release Notes",
    "path": "/kingshot-events/updates/release-notes",
    "navigationSection": "Updates",
    "audience": "All users",
    "experienceLevel": "All levels",
    "featureArea": "Updates",
    "publicationStatus": "published",
    "sortOrder": 140,
    "lastReviewedDate": "2026-08-01",
    "file": "kingshot-events/updates/release-notes.md"
  },
  {
    "product": "ralyvora-docs",
    "title": "About Ralyvora Docs",
    "path": "/about-ralyvora-docs",
    "navigationSection": "Support and Policies",
    "audience": "All visitors",
    "experienceLevel": "Beginner",
    "featureArea": "Trust",
    "publicationStatus": "published",
    "sortOrder": 150,
    "lastReviewedDate": "2026-08-01",
    "file": "about-ralyvora-docs.md"
  },
  {
    "product": "ralyvora-docs",
    "title": "Contact and Support",
    "path": "/support",
    "navigationSection": "Support and Policies",
    "audience": "All visitors",
    "experienceLevel": "Beginner",
    "featureArea": "Support",
    "publicationStatus": "published",
    "sortOrder": 151,
    "lastReviewedDate": "2026-08-01",
    "file": "support.md"
  },
  {
    "product": "ralyvora-docs",
    "title": "Editorial Policy",
    "path": "/editorial-policy",
    "navigationSection": "Support and Policies",
    "audience": "All visitors",
    "experienceLevel": "Beginner",
    "featureArea": "Editorial policy",
    "publicationStatus": "published",
    "sortOrder": 152,
    "lastReviewedDate": "2026-08-01",
    "file": "editorial-policy.md"
  },
  {
    "product": "ralyvora-docs",
    "title": "Privacy",
    "path": "/privacy",
    "navigationSection": "Support and Policies",
    "audience": "All visitors",
    "experienceLevel": "Beginner",
    "featureArea": "Privacy",
    "publicationStatus": "published",
    "sortOrder": 153,
    "lastReviewedDate": "2026-08-01",
    "file": "privacy.md"
  },
  {
    "product": "ralyvora-docs",
    "title": "Terms",
    "path": "/terms",
    "navigationSection": "Support and Policies",
    "audience": "All visitors",
    "experienceLevel": "Beginner",
    "featureArea": "Terms",
    "publicationStatus": "published",
    "sortOrder": 154,
    "lastReviewedDate": "2026-08-01",
    "file": "terms.md"
  },
  {
    "product": "ralyvora-docs",
    "title": "Copyright and Takedown",
    "path": "/copyright-and-takedown",
    "navigationSection": "Support and Policies",
    "audience": "All visitors",
    "experienceLevel": "Beginner",
    "featureArea": "Copyright",
    "publicationStatus": "published",
    "sortOrder": 155,
    "lastReviewedDate": "2026-08-01",
    "file": "copyright-and-takedown.md"
  },
  {
    "product": "kingshot-events",
    "title": "Redirect: getting-started/what-is-the-tracker",
    "path": "/getting-started/what-is-the-tracker",
    "file": "getting-started/what-is-the-tracker.md",
    "navigationSection": "Redirects",
    "audience": "Legacy visitors",
    "experienceLevel": "All levels",
    "featureArea": "Redirect",
    "publicationStatus": "redirect",
    "sortOrder": 1000,
    "lastReviewedDate": "2026-08-01",
    "redirectTo": "/kingshot-events/"
  },
  {
    "product": "kingshot-events",
    "title": "Redirect: getting-started/glossary",
    "path": "/getting-started/glossary",
    "file": "getting-started/glossary.md",
    "navigationSection": "Redirects",
    "audience": "Legacy visitors",
    "experienceLevel": "All levels",
    "featureArea": "Redirect",
    "publicationStatus": "redirect",
    "sortOrder": 1001,
    "lastReviewedDate": "2026-08-01",
    "redirectTo": "/kingshot-events/overview/terminology"
  },
  {
    "product": "kingshot-events",
    "title": "Redirect: getting-started/navigation-by-role",
    "path": "/getting-started/navigation-by-role",
    "file": "getting-started/navigation-by-role.md",
    "navigationSection": "Redirects",
    "audience": "Legacy visitors",
    "experienceLevel": "All levels",
    "featureArea": "Redirect",
    "publicationStatus": "redirect",
    "sortOrder": 1002,
    "lastReviewedDate": "2026-08-01",
    "redirectTo": "/kingshot-events/getting-started/access-and-navigation"
  },
  {
    "product": "kingshot-events",
    "title": "Redirect: how-to/players-directory",
    "path": "/how-to/players-directory",
    "file": "how-to/players-directory.md",
    "navigationSection": "Redirects",
    "audience": "Legacy visitors",
    "experienceLevel": "All levels",
    "featureArea": "Redirect",
    "publicationStatus": "redirect",
    "sortOrder": 1003,
    "lastReviewedDate": "2026-08-01",
    "redirectTo": "/kingshot-events/players/directory-and-profiles"
  },
  {
    "product": "kingshot-events",
    "title": "Redirect: how-to/add-player",
    "path": "/how-to/add-player",
    "file": "how-to/add-player.md",
    "navigationSection": "Redirects",
    "audience": "Legacy visitors",
    "experienceLevel": "All levels",
    "featureArea": "Redirect",
    "publicationStatus": "redirect",
    "sortOrder": 1004,
    "lastReviewedDate": "2026-08-01",
    "redirectTo": "/kingshot-events/players/manage-players"
  },
  {
    "product": "kingshot-events",
    "title": "Redirect: how-to/edit-player",
    "path": "/how-to/edit-player",
    "file": "how-to/edit-player.md",
    "navigationSection": "Redirects",
    "audience": "Legacy visitors",
    "experienceLevel": "All levels",
    "featureArea": "Redirect",
    "publicationStatus": "redirect",
    "sortOrder": 1005,
    "lastReviewedDate": "2026-08-01",
    "redirectTo": "/kingshot-events/players/manage-players"
  },
  {
    "product": "kingshot-events",
    "title": "Redirect: how-to/player-sync",
    "path": "/how-to/player-sync",
    "file": "how-to/player-sync.md",
    "navigationSection": "Redirects",
    "audience": "Legacy visitors",
    "experienceLevel": "All levels",
    "featureArea": "Redirect",
    "publicationStatus": "redirect",
    "sortOrder": 1006,
    "lastReviewedDate": "2026-08-01",
    "redirectTo": "/kingshot-events/players/linking-and-sync"
  },
  {
    "product": "kingshot-events",
    "title": "Redirect: how-to/delete-restore-player",
    "path": "/how-to/delete-restore-player",
    "file": "how-to/delete-restore-player.md",
    "navigationSection": "Redirects",
    "audience": "Legacy visitors",
    "experienceLevel": "All levels",
    "featureArea": "Redirect",
    "publicationStatus": "redirect",
    "sortOrder": 1007,
    "lastReviewedDate": "2026-08-01",
    "redirectTo": "/kingshot-events/players/lifecycle"
  },
  {
    "product": "kingshot-events",
    "title": "Redirect: how-to/manage-alliances",
    "path": "/how-to/manage-alliances",
    "file": "how-to/manage-alliances.md",
    "navigationSection": "Redirects",
    "audience": "Legacy visitors",
    "experienceLevel": "All levels",
    "featureArea": "Redirect",
    "publicationStatus": "redirect",
    "sortOrder": 1008,
    "lastReviewedDate": "2026-08-01",
    "redirectTo": "/kingshot-events/kingdoms-and-alliances/alliance-work"
  },
  {
    "product": "kingshot-events",
    "title": "Redirect: how-to/manage-kingdoms",
    "path": "/how-to/manage-kingdoms",
    "file": "how-to/manage-kingdoms.md",
    "navigationSection": "Redirects",
    "audience": "Legacy visitors",
    "experienceLevel": "All levels",
    "featureArea": "Redirect",
    "publicationStatus": "redirect",
    "sortOrder": 1009,
    "lastReviewedDate": "2026-08-01",
    "redirectTo": "/kingshot-events/kingdoms-and-alliances/kingdom-work"
  },
  {
    "product": "kingshot-events",
    "title": "Redirect: events/default-events",
    "path": "/events/default-events",
    "file": "events/default-events.md",
    "navigationSection": "Redirects",
    "audience": "Legacy visitors",
    "experienceLevel": "All levels",
    "featureArea": "Redirect",
    "publicationStatus": "redirect",
    "sortOrder": 1010,
    "lastReviewedDate": "2026-08-01",
    "redirectTo": "/kingshot-events/events/event-specific-behavior"
  },
  {
    "product": "kingshot-events",
    "title": "Redirect: how-to/manual-input",
    "path": "/how-to/manual-input",
    "file": "how-to/manual-input.md",
    "navigationSection": "Redirects",
    "audience": "Legacy visitors",
    "experienceLevel": "All levels",
    "featureArea": "Redirect",
    "publicationStatus": "redirect",
    "sortOrder": 1011,
    "lastReviewedDate": "2026-08-01",
    "redirectTo": "/kingshot-events/events/manual-entry"
  },
  {
    "product": "kingshot-events",
    "title": "Redirect: imports/overview",
    "path": "/imports/overview",
    "file": "imports/overview.md",
    "navigationSection": "Redirects",
    "audience": "Legacy visitors",
    "experienceLevel": "All levels",
    "featureArea": "Redirect",
    "publicationStatus": "redirect",
    "sortOrder": 1012,
    "lastReviewedDate": "2026-08-01",
    "redirectTo": "/kingshot-events/imports/screenshot-import"
  },
  {
    "product": "kingshot-events",
    "title": "Redirect: imports/upload-screenshots",
    "path": "/imports/upload-screenshots",
    "file": "imports/upload-screenshots.md",
    "navigationSection": "Redirects",
    "audience": "Legacy visitors",
    "experienceLevel": "All levels",
    "featureArea": "Redirect",
    "publicationStatus": "redirect",
    "sortOrder": 1013,
    "lastReviewedDate": "2026-08-01",
    "redirectTo": "/kingshot-events/imports/screenshot-import"
  },
  {
    "product": "kingshot-events",
    "title": "Redirect: imports/review-rows",
    "path": "/imports/review-rows",
    "file": "imports/review-rows.md",
    "navigationSection": "Redirects",
    "audience": "Legacy visitors",
    "experienceLevel": "All levels",
    "featureArea": "Redirect",
    "publicationStatus": "redirect",
    "sortOrder": 1014,
    "lastReviewedDate": "2026-08-01",
    "redirectTo": "/kingshot-events/imports/review-imported-data"
  },
  {
    "product": "kingshot-events",
    "title": "Redirect: analytics/overview",
    "path": "/analytics/overview",
    "file": "analytics/overview.md",
    "navigationSection": "Redirects",
    "audience": "Legacy visitors",
    "experienceLevel": "All levels",
    "featureArea": "Redirect",
    "publicationStatus": "redirect",
    "sortOrder": 1015,
    "lastReviewedDate": "2026-08-01",
    "redirectTo": "/kingshot-events/analytics/activity-and-results"
  },
  {
    "product": "kingshot-events",
    "title": "Redirect: how-to/rewards",
    "path": "/how-to/rewards",
    "file": "how-to/rewards.md",
    "navigationSection": "Redirects",
    "audience": "Legacy visitors",
    "experienceLevel": "All levels",
    "featureArea": "Redirect",
    "publicationStatus": "redirect",
    "sortOrder": 1016,
    "lastReviewedDate": "2026-08-01",
    "redirectTo": "/kingshot-events/analytics/rewards-and-statuses"
  },
  {
    "product": "kingshot-events",
    "title": "Redirect: castle-positions/overview",
    "path": "/castle-positions/overview",
    "file": "castle-positions/overview.md",
    "navigationSection": "Redirects",
    "audience": "Legacy visitors",
    "experienceLevel": "All levels",
    "featureArea": "Redirect",
    "publicationStatus": "redirect",
    "sortOrder": 1017,
    "lastReviewedDate": "2026-08-01",
    "redirectTo": "/kingshot-events/castle-positions/"
  },
  {
    "product": "kingshot-events",
    "title": "Redirect: castle-positions/applying",
    "path": "/castle-positions/applying",
    "file": "castle-positions/applying.md",
    "navigationSection": "Redirects",
    "audience": "Legacy visitors",
    "experienceLevel": "All levels",
    "featureArea": "Redirect",
    "publicationStatus": "redirect",
    "sortOrder": 1018,
    "lastReviewedDate": "2026-08-01",
    "redirectTo": "/kingshot-events/castle-positions/applicant-guide"
  },
  {
    "product": "kingshot-events",
    "title": "Redirect: castle-positions/reviewing",
    "path": "/castle-positions/reviewing",
    "file": "castle-positions/reviewing.md",
    "navigationSection": "Redirects",
    "audience": "Legacy visitors",
    "experienceLevel": "All levels",
    "featureArea": "Redirect",
    "publicationStatus": "redirect",
    "sortOrder": 1019,
    "lastReviewedDate": "2026-08-01",
    "redirectTo": "/kingshot-events/castle-positions/review-workflow"
  },
  {
    "product": "kingshot-events",
    "title": "Redirect: castle-positions/schedule-planner",
    "path": "/castle-positions/schedule-planner",
    "file": "castle-positions/schedule-planner.md",
    "navigationSection": "Redirects",
    "audience": "Legacy visitors",
    "experienceLevel": "All levels",
    "featureArea": "Redirect",
    "publicationStatus": "redirect",
    "sortOrder": 1020,
    "lastReviewedDate": "2026-08-01",
    "redirectTo": "/kingshot-events/castle-positions/planning-and-publishing"
  },
  {
    "product": "kingshot-events",
    "title": "Redirect: knowledge/overview",
    "path": "/knowledge/overview",
    "file": "knowledge/overview.md",
    "navigationSection": "Redirects",
    "audience": "Legacy visitors",
    "experienceLevel": "All levels",
    "featureArea": "Redirect",
    "publicationStatus": "redirect",
    "sortOrder": 1021,
    "lastReviewedDate": "2026-08-01",
    "redirectTo": "/kingshot-events/knowledge-hub/reading-and-finding"
  },
  {
    "product": "kingshot-events",
    "title": "Redirect: knowledge/authoring-and-review",
    "path": "/knowledge/authoring-and-review",
    "file": "knowledge/authoring-and-review.md",
    "navigationSection": "Redirects",
    "audience": "Legacy visitors",
    "experienceLevel": "All levels",
    "featureArea": "Redirect",
    "publicationStatus": "redirect",
    "sortOrder": 1022,
    "lastReviewedDate": "2026-08-01",
    "redirectTo": "/kingshot-events/knowledge-hub/authoring-and-publication"
  },
  {
    "product": "kingshot-events",
    "title": "Redirect: simulators/overview",
    "path": "/simulators/overview",
    "file": "simulators/overview.md",
    "navigationSection": "Redirects",
    "audience": "Legacy visitors",
    "experienceLevel": "All levels",
    "featureArea": "Redirect",
    "publicationStatus": "redirect",
    "sortOrder": 1023,
    "lastReviewedDate": "2026-08-01",
    "redirectTo": "/kingshot-events/lab/"
  },
  {
    "product": "kingshot-events",
    "title": "Redirect: simulators/hero-gear-reforge",
    "path": "/simulators/hero-gear-reforge",
    "file": "simulators/hero-gear-reforge.md",
    "navigationSection": "Redirects",
    "audience": "Legacy visitors",
    "experienceLevel": "All levels",
    "featureArea": "Redirect",
    "publicationStatus": "redirect",
    "sortOrder": 1024,
    "lastReviewedDate": "2026-08-01",
    "redirectTo": "/kingshot-events/lab/gear-and-charms"
  },
  {
    "product": "kingshot-events",
    "title": "Redirect: simulators/bear-trap-lab",
    "path": "/simulators/bear-trap-lab",
    "file": "simulators/bear-trap-lab.md",
    "navigationSection": "Redirects",
    "audience": "Legacy visitors",
    "experienceLevel": "All levels",
    "featureArea": "Redirect",
    "publicationStatus": "redirect",
    "sortOrder": 1025,
    "lastReviewedDate": "2026-08-01",
    "redirectTo": "/kingshot-events/lab/bear-rally-battle"
  },
  {
    "product": "kingshot-events",
    "title": "Redirect: subscriptions/overview",
    "path": "/subscriptions/overview",
    "file": "subscriptions/overview.md",
    "navigationSection": "Redirects",
    "audience": "Legacy visitors",
    "experienceLevel": "All levels",
    "featureArea": "Redirect",
    "publicationStatus": "redirect",
    "sortOrder": 1026,
    "lastReviewedDate": "2026-08-01",
    "redirectTo": "/kingshot-events/subscriptions/"
  },
  {
    "product": "kingshot-events",
    "title": "Redirect: roles/alliance-leader",
    "path": "/roles/alliance-leader",
    "file": "roles/alliance-leader.md",
    "navigationSection": "Redirects",
    "audience": "Legacy visitors",
    "experienceLevel": "All levels",
    "featureArea": "Redirect",
    "publicationStatus": "redirect",
    "sortOrder": 1027,
    "lastReviewedDate": "2026-08-01",
    "redirectTo": "/kingshot-events/role-journeys/alliance-leader"
  },
  {
    "product": "kingshot-events",
    "title": "Redirect: roles/co-leader",
    "path": "/roles/co-leader",
    "file": "roles/co-leader.md",
    "navigationSection": "Redirects",
    "audience": "Legacy visitors",
    "experienceLevel": "All levels",
    "featureArea": "Redirect",
    "publicationStatus": "redirect",
    "sortOrder": 1028,
    "lastReviewedDate": "2026-08-01",
    "redirectTo": "/kingshot-events/role-journeys/alliance-leader"
  },
  {
    "product": "kingshot-events",
    "title": "Redirect: roles/king",
    "path": "/roles/king",
    "file": "roles/king.md",
    "navigationSection": "Redirects",
    "audience": "Legacy visitors",
    "experienceLevel": "All levels",
    "featureArea": "Redirect",
    "publicationStatus": "redirect",
    "sortOrder": 1029,
    "lastReviewedDate": "2026-08-01",
    "redirectTo": "/kingshot-events/role-journeys/kingdom-manager"
  },
  {
    "product": "kingshot-events",
    "title": "Redirect: troubleshooting/login",
    "path": "/troubleshooting/login",
    "file": "troubleshooting/login.md",
    "navigationSection": "Redirects",
    "audience": "Legacy visitors",
    "experienceLevel": "All levels",
    "featureArea": "Redirect",
    "publicationStatus": "redirect",
    "sortOrder": 1030,
    "lastReviewedDate": "2026-08-01",
    "redirectTo": "/kingshot-events/troubleshooting/access-problems"
  },
  {
    "product": "kingshot-events",
    "title": "Redirect: troubleshooting/imports",
    "path": "/troubleshooting/imports",
    "file": "troubleshooting/imports.md",
    "navigationSection": "Redirects",
    "audience": "Legacy visitors",
    "experienceLevel": "All levels",
    "featureArea": "Redirect",
    "publicationStatus": "redirect",
    "sortOrder": 1031,
    "lastReviewedDate": "2026-08-01",
    "redirectTo": "/kingshot-events/troubleshooting/import-problems"
  }
]

export const publishedPages = publicationManifest.filter((entry) => entry.publicationStatus === 'published')
export const redirectPages = publicationManifest.filter((entry) => entry.publicationStatus === 'redirect')
